#!/bin/sh

WP_DB='whomwah_new'
NEW_DB_SQL='wp2.9.2.sql'
MIGRATION_SQL='migrate.sql'

echo "Build new empty database"
mysqladmin -f -uroot drop $WP_DB
mysqladmin -uroot create $WP_DB
echo "Add wordpress 2.9.2 schema"
mysql -uroot $WP_DB < $NEW_DB_SQL
echo "Load migration SQL"
mysql -uroot $WP_DB < $MIGRATION_SQL
echo "Done!"
